[tool.poetry]
name = "barcode_segmentation"
version = "0.1.0"
description = "Barcode Segmentation with Detectron2"
authors = ["Your Name <your.email@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
detectron2 = {url = "https://github.com/facebookresearch/detectron2.git"}
numpy = "^1.23.0"
opencv-python = "^4.0.0"
torch = "^1.13.0"
torchvision = "^0.14.0"
pyyaml = "^6.0"
tqdm = "^4.0.0"
dvc = "^3.0.0"
hydra-core = "^1.3"
fire = "^0.5.0"
pre-commit = "^3.0.0"
black = "^23.0"
isort = "^5.0"
flake8 = "^6.0"
prettier = "^2.0"
mlflow = "^2.0"
onnx = "^1.0"
nvidia-tensorrt = {url = "https://developer.download.nvidia.com/compute/redist/tensorrt/861/tars/TensorRT-8.6.1.6.Linux.x86_64-gnu.cuda-12.0.tar.gz"} # Поменять на актуальную версию

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
