weights_path: "outputs/model_final.pth"
device: "cuda"  # cuda или cpu
input_type: "directory"  # single_image или directory
input_path: "data/test"
output_dir: "inference_results"
save_visualizations: true

# Настройки для батчевого инференса
batch_size: 8
num_workers: 4

# Пороги
confidence_threshold: 0.7
nms_threshold: 0.5
