config_file: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
pretrained_weights: "model_zoo"  # или путь к весам
num_classes: 1
roi_batch_size: 128
score_threshold: 0.7

# Для продакшена
export:
  onnx:
    enabled: true
    output_path: "models/barcode_model.onnx"
    opset_version: 11
  tensorrt:
    enabled: true
    output_path: "models/barcode_model.trt"
    precision: "fp16"  # fp32, fp16, int8
