_target_: src.models.detectron_model.DetectronModel 

architecture: faster_rcnn 
backbone: resnet50 
num_classes: 2 # background + barcode 

model_config: 
  SOLVER: 
    IMS_PER_BATCH: 2 
    BASE_LR: 0.00025 
    MAX_ITER: 1000 
  DATALOADER: 
    NUM_WORKERS: 2 
