# Параметры планировщика обучения
scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 7
  gamma: 0.1

cosine_annealing:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 50
  eta_min: 1e-6
