defaults:
  - model: detectron2
  - data: coco
  - train: default
  - inference: default
  - _self_

# MLflow настройки
mlflow:
  tracking_uri: "http://127.0.0.1:8080"
  experiment_name: "barcode_detection"

# Общие настройки
project_name: "barcode-detection"
version: "1.0.0"

# Логирование
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
