defaults: 
  - model: detectron2 
  - data: coco 
  - training: default 
  - _self_ 

project_name: barcode_detection 
experiment_name: baseline 
random_seed: 42 

paths: 
  data_dir: data 
  model_dir: models 
  log_dir: logs 
