# @package _global_

# Глобальная конфигурация Hydra
defaults:
  - _self_
  - data: preprocessing  # Данные и предобработка
  - model: detectron2_maskrcnn  # Модель
  - training: optimizer  # Параметры обучения
  - training/scheduler: cosine  # Scheduler для LR

# Параметры проекта
project:
  name: "barcode_segmentation"
  version: "0.1.0"
  description: "MLOps проект для сегментации штрих-кодов"
  author: "Andreev Artem"
  email: "andreev.artem@phystech.edu"

# Пути к данным и моделям
data_dir: "${oc.env:PROJECT_ROOT,${hydra:runtime.cwd}}/data"
output_dir: "${oc.env:PROJECT_ROOT,${hydra:runtime.cwd}}/outputs"
model_dir: "${oc.env:PROJECT_ROOT,${hydra:runtime.cwd}}/models"
logs_dir: "${oc.env:PROJECT_ROOT,${hydra:runtime.cwd}}/logs"
plots_dir: "${oc.env:PROJECT_ROOT,${hydra:runtime.cwd}}/plots"

# MLflow настройки
mlflow:
  tracking_uri: "http://127.0.0.1:8080"
  experiment_name: "barcode_segmentation"
  register_model: true
  model_name: "barcode_maskrcnn"
  tags:
    model_type: "instance_segmentation"
    architecture: "mask_rcnn"
    backbone: "resnet50"

# Логирование
logging:
  level: "INFO"
  log_dir: "${logs_dir}"
  save_training_log: true
  log_to_console: true
  log_to_file: true
  log_to_mlflow: true

# Воспроизводимость
seed: 42

# Вычислительные ресурсы
resources:
  gpu_id: 0
  num_workers: 4
  pin_memory: true
  precision: 16

# Hydra настройки
hydra:
  # Директория для логов Hydra
  run:
    dir: ${logs_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  
  # Директория для multirun
  sweep:
    dir: ${logs_dir}/hydra/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  
  # Конфигурация логов Hydra
  job:
    chdir: true
  
  # Настройки для переопределения через CLI
  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        mode: w
        formatter: colorlog
        filename: ${hydra.run.dir}/hydra.log
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stdout
    formatters:
      simple:
        format: "[%(asctime)s][%(name)s][%(levelname)s] - %(message)s"
      colorlog:
        "()": colorlog.ColoredFormatter
        format: "[%(blue)s%(asctime)s%(reset)s][%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s] - %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
        log_colors:
          DEBUG: purple
          INFO: green
          WARNING: yellow
          ERROR: red
          CRITICAL: red,bg_white