defaults:
  - /config
  - _self_

deployment:
  input_model_path: "${model_dir}/best_model.ckpt"
  onnx:
    output_path: "${model_dir}/model.onnx"
    opset_version: 11
    dynamic_axes: true
    input_shape: [1, 3, 640, 640]
  tensorrt:
    output_path: "${model_dir}/model.trt"
    precision: "fp16"
    max_batch_size: 8
  triton:
    model_repository: "triton_models"
    model_name: "barcode_segmentation"
    model_version: 1
