defaults:
  - /config
  - _self_

# Параметры тренировки
training:
  max_epochs: 10
  val_check_interval: 1.0
  accelerator: "auto"
  devices: "auto"
  precision: 16
  gradient_clip_val: 1.0

# Checkpointing
checkpoint:
  monitor: "val_loss"
  mode: "min"
  save_top_k: 3
  every_n_epochs: 1

# Early stopping
early_stopping:
  monitor: "val_loss"
  patience: 5
  mode: "min"

# Логирование 
logging:
  log_every_n_steps: 50
  save_dir: "${plots_dir}"
